site_name: "python-app-1"
site_description: "Main documentation for the python-app-1"
repo_url: https://github.com/DaniloMirandaNG/python-app-1
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: "docs/index.md"
